In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('heart.csv')

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [17]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [18]:
X_train.shape

(242, 13)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [20]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [21]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\aashi\anaconda3\envs\Virt1\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [23]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

# Accuracy

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test,y_pred1)

0.9016393442622951

In [28]:
accuracy_score(y_test,y_pred2)

0.8360655737704918

# Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

In [31]:
confusion_matrix(y_test,y_pred2)

array([[25,  7],
       [ 3, 26]])

In [32]:
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

0   1
0  26   6
1   0  29

In [33]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [34]:
result

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
99              1                               1                         1
296             0                               1                         0
89              1                               1                         1
30              1                               1                         1
234             0                               0                         0
..            ...                             ...                       ...
173             0                               0                         1
94              1                               1                         1
161             1                               1                         1
216             0                               1                         1
91              1                               1                         1

[61 rows x 3 columns]

# Precision, Recall and F1_score

In [38]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [39]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625


In [41]:
print("For Decision Tree Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decision Tree Model
--------------------------------------------------
    0   1
0  25   7
1   3  26
--------------------------------------------------
Precision -  0.7878787878787878
Recall -  0.896551724137931
F1 score -  0.8387096774193549


In [43]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [44]:
recall_score(y_test,y_pred1,average=None)

array([0.8125, 1.    ])

In [49]:
f1_score(y_test,y_pred1,average=None)

array([0.89655172, 0.90625   ])