In [1]:
import numpy as np
import pickle
import pandas as pd

In [10]:
si_age = pickle.load(open('si_age.pkl','rb'))
si_embarked = pickle.load(open('si_embarked.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
ohe_sex = pickle.load(open('ohe_sex.pkl','rb'))
clf = pickle.load(open('clf.pkl','rb'))

In [74]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Embarked
test_input = np.array([1, 'female', 38.0, 1, 0, 'C'],dtype=object).reshape(1,6)

In [75]:
 test_input

array([[1, 'female', 38.0, 1, 0, 'C']], dtype=object)

# No need for Imputer since all values present

In [76]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [77]:
test_input_embarked

array([[1., 0., 0.]])

In [78]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\aashi\anaconda3\envs\Virt1\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [79]:
test_input_sex

array([[1., 0.]])

In [80]:
test_input_age = test_input[:,2].reshape(1,1)

In [81]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4]],test_input_age,test_input_embarked,test_input_sex),axis=1)

In [82]:
test_input_transformed

array([[1, 1, 0, 38.0, 1.0, 0.0, 0.0, 1.0, 0.0]], dtype=object)

In [83]:
clf.predict(test_input_transformed)

array([1])