In [5]:
# creating numpy/n-d arrays
import numpy as np


In [9]:
arr1 = np.array([1,2,3,4])
arr1


array([1, 2, 3, 4])

In [11]:
type(arr1)

numpy.ndarray

In [15]:
arr3 = np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr4 = np.ones((3,2))
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
arr5 = np.identity(5)
arr5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr7 = np.arange(5,20)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
arr8 = np.arange(5,20,3)
arr8

array([ 5,  8, 11, 14, 17])

In [35]:
arr9 = np.linspace(11,20,10)
arr9

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [41]:
# linearly spaced 
arr10 = np.linspace(20,50,10)
arr10

array([20.        , 23.33333333, 26.66666667, 30.        , 33.33333333,
       36.66666667, 40.        , 43.33333333, 46.66666667, 50.        ])

In [47]:
arr1.shape

(4,)

In [63]:
arr3 = np.array([[[2,2,23]],[[2,2,32]]])
arr3.shape

(2, 1, 3)

In [65]:
arr3.ndim


3

In [69]:
arr3.size


6

In [71]:
arr6.itemsize

4

In [75]:
arr4.itemsize


8

In [81]:
arr4.dtype

dtype('float64')

In [85]:
arr8.dtype

dtype('int32')

In [89]:
arr10.astype('int32')

array([20, 23, 26, 30, 33, 36, 40, 43, 46, 50])

In [103]:
# Numpy array VS python list

#1. Less Memory
lista = range(100)
arr11 = np.arange(100)

In [105]:
import sys

In [107]:
print(arr11.itemsize*len(arr11))

400


In [109]:
print(sys.getsizeof(lista[0]))

28


In [113]:
#2. Faster
import time


In [127]:
x = range(10000000)
y = range(10000000,20000000)

start_time=time.time()
c = [(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

1.3156111240386963


In [129]:
x = np.arange(10000000)
y = np.arange(10000000,20000000)

start_time=time.time()
c = x+y
print(time.time()-start_time)

0.39398670196533203
